# Generated by Django 5.2 on 2025-04-29 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Подтверждено'), ('completed', 'Завершено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='type_of_learning',
            field=models.CharField(choices=[('personal', 'Персональное'), ('group', 'Парное')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
