# Generated by Django 5.2 on 2025-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_enrollment_end_date_enrollment_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Подтверждено'), ('declined', 'Отклонено'), ('completed', 'Завершено')], default='pending', max_length=20),
        ),
    ]
